# Perissões
#
# - /fly - redefocus.commands.fly
# - /gamemode - redefocus.commands.gamemode
# - /tp - redefocus.commands.teleport
# - /ping - redefocus.commands.ping
# - /setspawn - redefocus.commands.setspawn
#

settings:
  network: '127.0.0.1:25565'
  spawn: '{"world":"world", "x": 0.0, "y": 4.0, "z": 0.0, "pitch": 0.0, "yaw": 0.0}'
  shop_url: ''
  tablist:
    header:
      - ''
      - '§6§lREDE FOCUS'
      - '    §floja.redefocus.com'
    footer:
      - ''
      - '§6§lREDES SOCIAIS'
      - '      §6Twitter: §ftwitter.com/RedeFocusMC'
      - '§6Discord: §fdiscord.redefocus.com'
  chat:
    tell:
      to: '§8[Mensagem para ${prefix}${username}§8]: §6${message}'
      from: '§8[Mensagem de ${prefix}${username}§8]: §6${message}'
    format: '${prefix}${username}§f: ${message}'
    permission: 'redefocus.chat.say'
    # Delay em segundos
    cooldown: 0
    bypass_permission: 'redefocus.chat.staff.cooldown.bypass'
  scoreboard:
    display_name: '§6§lREDE FOCUS'
    lines:
      - '§1'
      - '§f  Online: §b${network::online}'
      - '§2'
      - '§f   F. Legend: §a${legend::online}'
      - '§f   R. OverPower: §a${rankup::online}'
      - '§3'
      - '§f  Hub: §7#1'
      - '§4'
    footer: '§7  loja.redefocus.com'

servers:
  # Põe aqui da maneira q tá regitrado no bungee
  legend:
    display_name: 'Factions Legend'
    address: '127.0.0.1'
    port: 25565
    slots: 300
    slot: 11
    icon:
      id: 46
      data: 0
      display_name: '§bFactions Legend'
      lore:
        - ''
        - ' §7Convoque sua facção, construa sua base'
        - ' §7defenda-se de invasões adversárias'
        - ' §7e realize suas própias invasões.'
        - ''
        - '   §6* §fEconomia Mediana.'
        - '   §6* §fSistema de habilidades exclusivo'
        - '   §6* §fSistema de mineração exclusivo'
        - '   §6* §fSistema de missões exclusivo'
        - '   §6* §fSistema de mobcoins exclusivo'
        - '   §6* §fSistema de theend exclusivo'
        - '   §6* §fSistema de facção exclusivo'
        - '   §6* §fSistema de encantamentos exclusivo.'
        - '   §6* §fCaixas Misteriosas exclusivas'
        - '   §6* §fE muito Mais!'
        - ''
        - '§aClique para entrar'
  rankup:
    display_name: 'Rankup Over Power'
    address: '127.0.0.1'
    port: 25565
    slots: 300
    slot: 13
    icon:
      id: 278
      data: 0
      display_name: '§bRankUP OverPower'
      lore:
        - ''
        - ' §7Convoque seu clan, conquiste seus'
        - ' §7spawners, finalize todos ranks'
        - ' §7e domine o servidor junto com seu clan!'
        - ''
        - '   §6* §fEconomia OP'
        - '   §6* §fSistema de Crates exclusivo'
        - '   §6* §fSistema de Ranks exclusivo'
        - '   §6* §fSistema de Itens Edit exclusivo'
        - '   §6* §fSistema de Maquinas exclusivo'
        - '   §6* §fSistema de Spawners exclusivo'
        - '   §6* §fSistema de Clan exclusivo'
        - '   §6* §fSistema de encantamentos exclusivo.'
        - '   §6* §fE muito Mais!'
        - ''
        - '§aClique para entrar'
  empire:
    display_name: 'Factions Empire'
    address: '127.0.0.1'
    port: 25565
    slots: 300
    slot: 15
    icon:
      id: 120
      data: 0
      display_name: '§bFactions Empire OP'
      lore:
        - ''
        - ' §7Convoque sua facção, construa sua base'
        - ' §7defenda-se de invasões adversárias'
        - ' §7e realize suas própias invasões.'
        - ''
        - '   §6* §fEconomia Mediana.'
        - '   §6* §fMundo Customizado.'
        - '   §6* §fSistema de habilidades exclusivo'
        - '   §6* §fSistema de mineração exclusivo'
        - '   §6* §fSistema de recompenças exclusivo'
        - '   §6* §fSistema de missões exclusivo'
        - '   §6* §fSistema de mobcoins exclusivo'
        - '   §6* §fSistema de theend exclusivo'
        - '   §6* §fSistema de facção exclusivo'
        - '   §6* §fSistema de encantamentos exclusivo.'
        - '   §6* §fCaixas Misteriosas exclusivas'
        - ''
        - '§aClique para entrar'